"""Add invitations_quota to employer_profile

Revision ID: 5f8479ef9e61
Revises: 816518ac58b2
Create Date: 2026-03-15 14:08:21.993861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8479ef9e61'
down_revision = '816518ac58b2'
branch_labels = None
depends_on = None


def upgrade():
    # Для SQLite нельзя добавить NOT NULL колонку без значения по умолчанию.
    # Поэтому сначала добавляем колонку с server_default=10, затем убираем default.
    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'invitations_quota',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('10'),
            )
        )

    # После применения миграции можно (в других СУБД) убрать server_default,
    # но для SQLite это не обязательно и безопасно оставить как есть.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer_profile', schema=None) as batch_op:
        batch_op.drop_column('invitations_quota')

    # ### end Alembic commands ###
