"""grades_stars_tokens_characteristics

Revision ID: 816518ac58b2
Revises: 
Create Date: 2026-02-01 23:09:20.491878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816518ac58b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'characteristic_id', name='uq_subject_characteristic')
    )
    op.create_table('token_award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('knowledge')
        batch_op.drop_column('diligence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diligence', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('knowledge', sa.INTEGER(), nullable=False))

    op.drop_table('token_award')
    op.drop_table('subject_characteristic')
    op.drop_table('characteristic')
    # ### end Alembic commands ###
